# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/luca/Desktop/Testing/progetto_finale

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/luca/Desktop/Testing/progetto_finale

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luca/Desktop/Testing/progetto_finale/CMakeFiles /home/luca/Desktop/Testing/progetto_finale//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luca/Desktop/Testing/progetto_finale/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named battaglia_navale

# Build rule for target.
battaglia_navale: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 battaglia_navale
.PHONY : battaglia_navale

# fast build rule for target.
battaglia_navale/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/build
.PHONY : battaglia_navale/fast

#=============================================================================
# Target rules for targets named replay

# Build rule for target.
replay: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 replay
.PHONY : replay

# fast build rule for target.
replay/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/build
.PHONY : replay/fast

src/battaglia_navale.o: src/battaglia_navale.cpp.o
.PHONY : src/battaglia_navale.o

# target to build an object file
src/battaglia_navale.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/battaglia_navale.cpp.o
.PHONY : src/battaglia_navale.cpp.o

src/battaglia_navale.i: src/battaglia_navale.cpp.i
.PHONY : src/battaglia_navale.i

# target to preprocess a source file
src/battaglia_navale.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/battaglia_navale.cpp.i
.PHONY : src/battaglia_navale.cpp.i

src/battaglia_navale.s: src/battaglia_navale.cpp.s
.PHONY : src/battaglia_navale.s

# target to generate assembly for a file
src/battaglia_navale.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/battaglia_navale.cpp.s
.PHONY : src/battaglia_navale.cpp.s

src/bot.o: src/bot.cpp.o
.PHONY : src/bot.o

# target to build an object file
src/bot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/bot.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/bot.cpp.o
.PHONY : src/bot.cpp.o

src/bot.i: src/bot.cpp.i
.PHONY : src/bot.i

# target to preprocess a source file
src/bot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/bot.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/bot.cpp.i
.PHONY : src/bot.cpp.i

src/bot.s: src/bot.cpp.s
.PHONY : src/bot.s

# target to generate assembly for a file
src/bot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/bot.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/bot.cpp.s
.PHONY : src/bot.cpp.s

src/grid/attack_grid.o: src/grid/attack_grid.cpp.o
.PHONY : src/grid/attack_grid.o

# target to build an object file
src/grid/attack_grid.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/grid/attack_grid.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/grid/attack_grid.cpp.o
.PHONY : src/grid/attack_grid.cpp.o

src/grid/attack_grid.i: src/grid/attack_grid.cpp.i
.PHONY : src/grid/attack_grid.i

# target to preprocess a source file
src/grid/attack_grid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/grid/attack_grid.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/grid/attack_grid.cpp.i
.PHONY : src/grid/attack_grid.cpp.i

src/grid/attack_grid.s: src/grid/attack_grid.cpp.s
.PHONY : src/grid/attack_grid.s

# target to generate assembly for a file
src/grid/attack_grid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/grid/attack_grid.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/grid/attack_grid.cpp.s
.PHONY : src/grid/attack_grid.cpp.s

src/grid/defense_grid.o: src/grid/defense_grid.cpp.o
.PHONY : src/grid/defense_grid.o

# target to build an object file
src/grid/defense_grid.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/grid/defense_grid.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/grid/defense_grid.cpp.o
.PHONY : src/grid/defense_grid.cpp.o

src/grid/defense_grid.i: src/grid/defense_grid.cpp.i
.PHONY : src/grid/defense_grid.i

# target to preprocess a source file
src/grid/defense_grid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/grid/defense_grid.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/grid/defense_grid.cpp.i
.PHONY : src/grid/defense_grid.cpp.i

src/grid/defense_grid.s: src/grid/defense_grid.cpp.s
.PHONY : src/grid/defense_grid.s

# target to generate assembly for a file
src/grid/defense_grid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/grid/defense_grid.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/grid/defense_grid.cpp.s
.PHONY : src/grid/defense_grid.cpp.s

src/grid/grid.o: src/grid/grid.cpp.o
.PHONY : src/grid/grid.o

# target to build an object file
src/grid/grid.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/grid/grid.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/grid/grid.cpp.o
.PHONY : src/grid/grid.cpp.o

src/grid/grid.i: src/grid/grid.cpp.i
.PHONY : src/grid/grid.i

# target to preprocess a source file
src/grid/grid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/grid/grid.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/grid/grid.cpp.i
.PHONY : src/grid/grid.cpp.i

src/grid/grid.s: src/grid/grid.cpp.s
.PHONY : src/grid/grid.s

# target to generate assembly for a file
src/grid/grid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/grid/grid.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/grid/grid.cpp.s
.PHONY : src/grid/grid.cpp.s

src/replay.o: src/replay.cpp.o
.PHONY : src/replay.o

# target to build an object file
src/replay.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/replay.cpp.o
.PHONY : src/replay.cpp.o

src/replay.i: src/replay.cpp.i
.PHONY : src/replay.i

# target to preprocess a source file
src/replay.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/replay.cpp.i
.PHONY : src/replay.cpp.i

src/replay.s: src/replay.cpp.s
.PHONY : src/replay.s

# target to generate assembly for a file
src/replay.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/replay.cpp.s
.PHONY : src/replay.cpp.s

src/ship/corazzata.o: src/ship/corazzata.cpp.o
.PHONY : src/ship/corazzata.o

# target to build an object file
src/ship/corazzata.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/ship/corazzata.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/ship/corazzata.cpp.o
.PHONY : src/ship/corazzata.cpp.o

src/ship/corazzata.i: src/ship/corazzata.cpp.i
.PHONY : src/ship/corazzata.i

# target to preprocess a source file
src/ship/corazzata.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/ship/corazzata.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/ship/corazzata.cpp.i
.PHONY : src/ship/corazzata.cpp.i

src/ship/corazzata.s: src/ship/corazzata.cpp.s
.PHONY : src/ship/corazzata.s

# target to generate assembly for a file
src/ship/corazzata.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/ship/corazzata.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/ship/corazzata.cpp.s
.PHONY : src/ship/corazzata.cpp.s

src/ship/empty.o: src/ship/empty.cpp.o
.PHONY : src/ship/empty.o

# target to build an object file
src/ship/empty.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/ship/empty.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/ship/empty.cpp.o
.PHONY : src/ship/empty.cpp.o

src/ship/empty.i: src/ship/empty.cpp.i
.PHONY : src/ship/empty.i

# target to preprocess a source file
src/ship/empty.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/ship/empty.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/ship/empty.cpp.i
.PHONY : src/ship/empty.cpp.i

src/ship/empty.s: src/ship/empty.cpp.s
.PHONY : src/ship/empty.s

# target to generate assembly for a file
src/ship/empty.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/ship/empty.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/ship/empty.cpp.s
.PHONY : src/ship/empty.cpp.s

src/ship/esploratore.o: src/ship/esploratore.cpp.o
.PHONY : src/ship/esploratore.o

# target to build an object file
src/ship/esploratore.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/ship/esploratore.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/ship/esploratore.cpp.o
.PHONY : src/ship/esploratore.cpp.o

src/ship/esploratore.i: src/ship/esploratore.cpp.i
.PHONY : src/ship/esploratore.i

# target to preprocess a source file
src/ship/esploratore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/ship/esploratore.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/ship/esploratore.cpp.i
.PHONY : src/ship/esploratore.cpp.i

src/ship/esploratore.s: src/ship/esploratore.cpp.s
.PHONY : src/ship/esploratore.s

# target to generate assembly for a file
src/ship/esploratore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/ship/esploratore.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/ship/esploratore.cpp.s
.PHONY : src/ship/esploratore.cpp.s

src/ship/movement.o: src/ship/movement.cpp.o
.PHONY : src/ship/movement.o

# target to build an object file
src/ship/movement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/ship/movement.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/ship/movement.cpp.o
.PHONY : src/ship/movement.cpp.o

src/ship/movement.i: src/ship/movement.cpp.i
.PHONY : src/ship/movement.i

# target to preprocess a source file
src/ship/movement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/ship/movement.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/ship/movement.cpp.i
.PHONY : src/ship/movement.cpp.i

src/ship/movement.s: src/ship/movement.cpp.s
.PHONY : src/ship/movement.s

# target to generate assembly for a file
src/ship/movement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/ship/movement.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/ship/movement.cpp.s
.PHONY : src/ship/movement.cpp.s

src/ship/ship.o: src/ship/ship.cpp.o
.PHONY : src/ship/ship.o

# target to build an object file
src/ship/ship.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/ship/ship.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/ship/ship.cpp.o
.PHONY : src/ship/ship.cpp.o

src/ship/ship.i: src/ship/ship.cpp.i
.PHONY : src/ship/ship.i

# target to preprocess a source file
src/ship/ship.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/ship/ship.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/ship/ship.cpp.i
.PHONY : src/ship/ship.cpp.i

src/ship/ship.s: src/ship/ship.cpp.s
.PHONY : src/ship/ship.s

# target to generate assembly for a file
src/ship/ship.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/ship/ship.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/ship/ship.cpp.s
.PHONY : src/ship/ship.cpp.s

src/ship/supporto.o: src/ship/supporto.cpp.o
.PHONY : src/ship/supporto.o

# target to build an object file
src/ship/supporto.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/ship/supporto.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/ship/supporto.cpp.o
.PHONY : src/ship/supporto.cpp.o

src/ship/supporto.i: src/ship/supporto.cpp.i
.PHONY : src/ship/supporto.i

# target to preprocess a source file
src/ship/supporto.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/ship/supporto.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/ship/supporto.cpp.i
.PHONY : src/ship/supporto.cpp.i

src/ship/supporto.s: src/ship/supporto.cpp.s
.PHONY : src/ship/supporto.s

# target to generate assembly for a file
src/ship/supporto.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/ship/supporto.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/ship/supporto.cpp.s
.PHONY : src/ship/supporto.cpp.s

src/utility.o: src/utility.cpp.o
.PHONY : src/utility.o

# target to build an object file
src/utility.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/utility.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/utility.cpp.o
.PHONY : src/utility.cpp.o

src/utility.i: src/utility.cpp.i
.PHONY : src/utility.i

# target to preprocess a source file
src/utility.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/utility.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/utility.cpp.i
.PHONY : src/utility.cpp.i

src/utility.s: src/utility.cpp.s
.PHONY : src/utility.s

# target to generate assembly for a file
src/utility.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/utility.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/utility.cpp.s
.PHONY : src/utility.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... battaglia_navale"
	@echo "... replay"
	@echo "... src/battaglia_navale.o"
	@echo "... src/battaglia_navale.i"
	@echo "... src/battaglia_navale.s"
	@echo "... src/bot.o"
	@echo "... src/bot.i"
	@echo "... src/bot.s"
	@echo "... src/grid/attack_grid.o"
	@echo "... src/grid/attack_grid.i"
	@echo "... src/grid/attack_grid.s"
	@echo "... src/grid/defense_grid.o"
	@echo "... src/grid/defense_grid.i"
	@echo "... src/grid/defense_grid.s"
	@echo "... src/grid/grid.o"
	@echo "... src/grid/grid.i"
	@echo "... src/grid/grid.s"
	@echo "... src/replay.o"
	@echo "... src/replay.i"
	@echo "... src/replay.s"
	@echo "... src/ship/corazzata.o"
	@echo "... src/ship/corazzata.i"
	@echo "... src/ship/corazzata.s"
	@echo "... src/ship/empty.o"
	@echo "... src/ship/empty.i"
	@echo "... src/ship/empty.s"
	@echo "... src/ship/esploratore.o"
	@echo "... src/ship/esploratore.i"
	@echo "... src/ship/esploratore.s"
	@echo "... src/ship/movement.o"
	@echo "... src/ship/movement.i"
	@echo "... src/ship/movement.s"
	@echo "... src/ship/ship.o"
	@echo "... src/ship/ship.i"
	@echo "... src/ship/ship.s"
	@echo "... src/ship/supporto.o"
	@echo "... src/ship/supporto.i"
	@echo "... src/ship/supporto.s"
	@echo "... src/utility.o"
	@echo "... src/utility.i"
	@echo "... src/utility.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

